// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/portfolio/BoldColorful.tsx": () => import("../components/mockups/portfolio/BoldColorful.tsx"),
  "./components/mockups/portfolio/DarkNoir.tsx": () => import("../components/mockups/portfolio/DarkNoir.tsx"),
  "./components/mockups/portfolio/MinimalistLight.tsx": () => import("../components/mockups/portfolio/MinimalistLight.tsx")
};
